config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_articles, only: [:index]
  before_action :set_article, only: [:edit, :show]

  def index; end

  def show; end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    go_home
  end

  def edit; end

  def update
    set_article
    @article.update(article_params)
    go_home
  end

  def destroy
    set_article.destroy
    go_home
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_articles
    @articles = Article.all
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def go_home
    redirect_to articles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title %>

  <%= f.label :content  %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Edit</h1>
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

<%= link_to "Add Article", new_article_path %>

<ul>
  <% @articles.each do |article| %>
    <li> <%= link_to article.title, article_path(article) %> </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1>New Article!</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>

<%= link_to "Edit it", edit_article_path %>
<%= link_to "Annihilate it", article_path(@article),
    method: :delete,
    data: {confirm: "Sure you want to destroy #{@article.title}?"} %>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>